[package]
name = "south-common"
version = "2.0.0"
edition = "2024"

[features]
default = [ ]

g0 = [ "embedded", "embassy-stm32/stm32g0b1ke" ]
h7 = [ "embedded", "embassy-stm32/stm32h723vg" ]
alloc = [ ]

embedded = [ "embassy-stm32", "defmt", "heapless", "embedded-can" ]
serde = ["tmtc-system/serde", "alloc" ]

[dependencies]
tmtc-system = { version = "3.1.1", git = "ssh://git@github.com/S2outh/telemetry-system.git" }
#tmtc-system = { version = "1.0.0", path = "/home/eliseoc/WueSpace/South/tmtc-system" }

# air
embassy-stm32 = { version = "0.5.0", features = [ "defmt" ], optional = true }
defmt = { version = "1.0", optional = true }
heapless = { version = "0.9", default-features = false, optional = true }
embedded-can = { version = "0.4.1", optional = true }
