[package]
name = "south-common"
version = "4.0.0"
edition = "2024"

[features]
default = [ ]

g0 = [ "embedded", "embassy-stm32/stm32g0b1ke" ]
h7 = [ "embedded", "embassy-stm32/stm32h723vg" ]

embedded = [ "embassy-stm32", "defmt", "heapless", "embedded-can" ]
ground = ["chell/ground", "dep:serde", "dep:libm" ]

[dependencies]
chell = { git = "https://github.com/S2outh/chell-sys.git" }

# config
lsm6dsv32 = { git = "ssh://git@github.com/S2outh/imu-driver.git", default-features = false }
spin = { version = "0.10.0", features = ["lazy", "portable-atomic"], default-features = false }

# air
embassy-stm32 = { version = "0.6.0", features = [ "defmt" ], optional = true }
defmt = { version = "1.0", optional = true }
heapless = { version = "0.9", default-features = false, optional = true }
embedded-can = { version = "0.4.1", optional = true }

# ground
libm = { version = "0.2.16", optional = true }
serde = { version = "1.0.228", default-features = false, features = ["derive"], optional = true }
bitflags = { version = "2.11.0", features = ["serde"] }

[build-dependencies]
serde_json = "1.0.149"
serde = { version = "1.0.228", features = ["derive"] }
